#
# This is a small test for scaling laws.
#

###############################################################
# AUTOEXP.
# Special variables used by autoexp and some common paths.

autoexp:

    # A folder for this example. Make sure the subfolders exist.
    folder: "/leonardo/home/userexternal/najroldi/oellm/dev/autoexperiment/examples/oellm_sweep"
    templates: "{folder}/templates"
    cluster: "{folder}/cluster"
    helpers: "{folder}/helpers"
    logs: "{folder}/logs"
    ckpts: "{logs}/checkpoints"

    # Templated sbatch.
    template: "{templates}/train.sbatch"

    # Destination script and command.
    sbatch_script: "{folder}/generated/{name}.sbatch"
    cmd: "sbatch {sbatch_script}"

    # A unique name.
    name: "test3_lr{args.lr}_iters{args.train_iters}"

    # Termination cmd.
    termination_cmd: "{helpers}/finished_train.py {logs} {slurm.job_name}"

###############################################################
# TEMPLATE ARGS.
# Placeholders in the templated sbatch.

slurm:

    job_name: "{autoexp.name}"
    out_dir: "{autoexp.logs}"

    account: "AIFAC_L01_028"
    partition: boost_usr_prod
    qos: "boost_qos_dbg"
    nnodes: 1

    cluster_setup_script: "{autoexp.cluster}/setup_leonardo.sh"

###############################################################
# MEGATRON ARGS.
# Variable starting with `_` are intermediate variables.
# All the other args are concatenated and passed verbatim to Megatron-LM.
# If you want to sweep over some vars, move them to `experiments` section.

args:

    # wandb name
    wandb_exp_name: "{autoexp.name}"
    wandb_project: oellm-train

    # TOKENS
    _tokens: 204800
    train_iters: "expr(({_tokens} + {seq_length} * {global_batch_size} - 1) // ({seq_length} * {global_batch_size}))"

    # LR DECAY
    _lr_decay_fraction: 0.2
    lr_decay_iters: "expr(int({train_iters} * {_lr_decay_fraction}))"
    lr_wsd_decay_iters: "expr(int({train_iters} * {_lr_decay_fraction}))"

    # DATA
    data_path: [
      /leonardo_work/AIFAC_L01_028/najroldi/datasets/Nemotron-cc-2024-HQ-real-synth-mix/GPT-NeoX/merged_0,
      /leonardo_work/AIFAC_L01_028/najroldi/datasets/Nemotron-cc-2024-HQ-real-synth-mix/GPT-NeoX/merged_1,
      /leonardo_work/AIFAC_L01_028/najroldi/datasets/Nemotron-cc-2024-HQ-real-synth-mix/GPT-NeoX/merged_2,
      /leonardo_work/AIFAC_L01_028/najroldi/datasets/Nemotron-cc-2024-HQ-real-synth-mix/GPT-NeoX/merged_3,
      /leonardo_work/AIFAC_L01_028/najroldi/datasets/Nemotron-cc-2024-HQ-real-synth-mix/GPT-NeoX/merged_4,
      /leonardo_work/AIFAC_L01_028/najroldi/datasets/Nemotron-cc-2024-HQ-real-synth-mix/GPT-NeoX/merged_5  
    ]
    seq_length: 2048
    max_position_embeddings: 2048
    micro_batch_size: 25
    global_batch_size: 100
    vocab_file: "/leonardo_work/AIFAC_L01_028/najroldi/models/EleutherAI/gpt-neox-20b/vocab.json"
    merge_file: "/leonardo_work/AIFAC_L01_028/najroldi/models/EleutherAI/gpt-neox-20b/merges.txt"
    num_workers: 8
    split: '99,1,0'

    # MODEL: 10M
    num_layers: 5
    hidden_size: 160
    ffn_hidden_size: 640
    num_attention_heads: 4
    init_method_std: 0.02
    position_embedding_type: "rope"
    rotary_base: 10000
    rotary_percent: 1.0
    group_query_attentions: False
    num_query_groups: 8 # no gqa when NUM_QUERY_GROUPS==NUM_ATTENTION_HEADS TODO: check
    attention_dropout: 0.0
    hidden_dropout: 0.0
    normalization: RMSNorm
    norm_epsilon: 1.e-5 # rmsnorm epsilon
    qk_layernorm: False # potentially enable qk-norm
    bf16: True
    swiglu: True
    untie_embeddings_and_output_weights: False
    use_flash_attn: True
    attention_softmax_in_fp32: False
    disable_bias_linear: True

    # these args substantially improve TFLOP/s/GPU (1.7B model on 54 nodes, 160 vs 140 with vs without)
    overlap_param_gather: True
    overlap_grad_reduce: True
    overlap_param_gather_with_optimizer_step: False # with interleaved pipeline parallelism

    # TRAINING, PARALLELISM
    recompute_activations: False
    use_torch_fsdp2: False # it's either this or the next 4 args
    tensor_model_parallel_size: 1
    pipeline_model_parallel_size: 1
    context_parallel_size: 1
    sequence_parallel: True

    # num_layers_per_virtual_pipeline_stage: null # interleaved pipeline scheduling is only possible with pipeline parallel degree > 1.
    use_distributed_optimizer: True

    distributed_backend: nccl
    distributed_timeout_minutes: 10

    # OPTIMIZER
    optimizer: adam
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.e-8
    min_lr: 0.0
    lr_decay_style: WSD
    lr_wsd_decay_style: linear
    clip_grad: 1.0
    weight_decay: 0.05

    # PROFILE
    profile: False
    use_pytorch_profiler: False
    profile_ranks: [0]
    profile_step_start: 5
    profile_step_end: 12

    # EVALS
    eval_interval: 72661
    eval_iters: 1

    # LOGGING
    log_interval: 1
    log_progress: True
    log_throughput: True
    tensorboard_queue_size: 5

    # Set CHECKPOINT_FORMAT
    ckpt_format: "torch" # "torch_dist" is currently bugged
    save_interval: 10


###############################################################
# OPTIONAL EXPERIMENT SETUP.
# This allows to easily distinguish between megatron args, slurm args, and intermediate variables.

experiments:
    args.lr: 1.e-2
    # args.lr: [1.e-2, 1.e-1]

    duration:
        # - short:
        #     args._tokens: 204800 # one iteration
        #     args.log_interval: 1
        - long:
            args._tokens: 2048000 # 10 iterations
            args.log_interval: 2
